name: Send Study Reminders

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 min UTC
  workflow_dispatch:

jobs:
  reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          curl -X GET "https://quiet-hours-scheduler.vercel.app/api/cron/send-reminders?cron_secret=${{ secrets.CRON_SECRET }}"
