name: Trigger Reminder Cron

on:
  schedule:
    - cron: "0 9 * * *"   # runs every day at 9 AM UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Call your Vercel API route
        run: |
          curl -X POST "https://manish-reminder-app.vercel.app/api/send-email"
