name: Send Reminders

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Ping reminder API
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl -s -o /dev/null -w "%{http_code}" "$SITE_URL/api/cron/send-reminders?cron_secret=$CRON_SECRET"
