name: Send Reminders

on:
  schedule:
    # Runs every day at 9:00 UTC
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Reminder API
        run: |
          curl -X POST "https://quiet-hours-scheduler.vercel.app/api/cron/send-reminders?cron_secret=${{ secrets.CRON_SECRET }}"
